language: android

jdk:
 - oraclejdk7
 - oraclejdk8

android:
  components:
    - build-tools-30.0.2
    - android-23

    # Update Android SDK Tools
    - tools

branches:
  except:
    - gh-pages

notifications:
  email: false
